spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

application:
  title: '@project.artifactId@'
  version: '@project.version@'

integrations:
  viacep:
    url: viacep.com.br
    name: viacep
